version: '3.9'

services:
  app2:
    image: ruby:3.3
    container_name: app2
    tty: true
    env_file:
      - .env
    working_dir: /app
    ports:
      - "3002:3002"
    volumes:
      - .:/app
      - rubygems:/usr/local/bundle
    depends_on:
      - postgres
      - rabbitmq
    entrypoint: ./entrypoint.sh
    environment:
      - PORT=3002
    command: "bin/dev"
    networks:
      - default
      - rabbitmq_network

  postgres:
    image: postgres
    container_name: app2-db
    environment:
      POSTGRES_DB: primarydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - database:/var/lib/postgresql/data

  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3.12-management"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - rabbitmq_network

volumes:
  rubygems:
  database:
  rabbitmq-data:

networks:
  rabbitmq_network:
    name: rabbitmq_network
    external: true
